name: Regression

on: [push, pull_request]

branches:
  - master

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rust: [stable]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: BUILDENV
        shell: bash
        run: |
          rm -f BUILDENV
          rustup --version >> BUILDENV
          cargo --version >> BUILDENV
          rustc --version >> BUILDENV
          cat BUILDENV
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('BUILDENV', '**/Cargo.lock') }}
      - run: cargo test
      - name: Run with every ruleset TOML configuration.
        shell: bash
        run: |
          for r in rulesets/*.toml; do
            SVLINT_CONFIG="$r" cargo run -- \
              testcases/application/resources/must_pass_all_rulesets.sv
          done
